---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.fullname" . }}-configmap
  labels:
    {{- include "helper.labels" . | nindent 4 }}
data:
  application-rulbackendservice.properties: |-
    cloud.accessKey={{ .Values.credentials.cloud.accessKey }}
    cloud.secretKey={{ .Values.credentials.cloud.secretKey }}
    edc.apiwrapper.username={{ .Values.credentials.apiwrapper.username }}
    edc.apiwrapper.password={{ .Values.credentials.apiwrapper.password }}
    security.api.username={{ .Values.credentials.api.username }}
    security.api.password={{ .Values.credentials.api.password }}
    rawdatadb.username={{ .Values.credentials.rawdata.username }}
    rawdatadb.password={{ .Values.credentials.rawdata.password }}
    ruldb.username={{ .Values.credentials.rul.username }}
    ruldb.password={{ .Values.credentials.rul.password }}
    server.port={{ .Values.server.port }}
    {{- .Values.configuration.properties | nindent 4 }}
