---
apiVersion: v2
name: sedc-oem-datacollector-edc-debug
description: sedc-oem-datacollector-edc-debug
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.1.0"
version: 0.1.0
maintainers: []
