package net.catena_x.btp.libraries.edc.model.transfer;

public enum TransferState {
    INITIAL,
    PROVISIONING,
    PROVISIONING_REQUESTED,
    PROVISIONED,
    REQUESTING,
    REQUESTED,
    STARTING,
    STARTED,
    SUSPENDING,
    SUSPENDED,
    COMPLETING,
    COMPLETED,
    TERMINATING,
    TERMINATED,
    DEPROVISIONING,
    DEPROVISIONING_REQUESTED,
    DEPROVISIONED
}