---
apiVersion: v2
name: oem-hi-frontend
description: oem-hi-app
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.1.0"
version: 0.1.0
maintainers: []
