---
apiVersion: v2
name: oem-hi-frontend
description: oem-hi-app
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.0.1"
version: 0.0.1
maintainers: []
