---
credentials:
  cloud:
    accessKey: &cloudKey <path:behaviour-twin-pilot/data/dlr/minio#accessKey>
    secretKey: &cloudSecret <path:behaviour-twin-pilot/data/dlr/minio#secretKey>
  apiwrapper:
    username: &apiwrapperUser <path:behaviour-twin-pilot/data/health-indicator/credentials/apiwrapper#username>
    password: &apiwrapperPass <path:behaviour-twin-pilot/data/health-indicator/credentials/apiwrapper#password>
  api:
    username: &apiUser <path:behaviour-twin-pilot/data/health-indicator/credentials/api#username>
    password: &apiPass <path:behaviour-twin-pilot/data/health-indicator/credentials/api#password>
  rawdata:
    username: &rawdataUser <path:behaviour-twin-pilot/data/health-indicator/credentials/rawdata#username>
    password: &rawdataPass <path:behaviour-twin-pilot/data/health-indicator/credentials/rawdata#password>
  rul:
    username: &hiUser <path:behaviour-twin-pilot/data/health-indicator/credentials/healthindicator#username>
    password: &hiPass <path:behaviour-twin-pilot/data/health-indicator/credentials/healthindicator#password>


rulbackend:
  ingress:
    enabled: true
    className: ""
    tls: true
    certManager:
      issuer: ""
      clusterIssuer: ""

    annotations: {}
    hostname: "bmw-rul-backend.dev.demo.catena-x.net"
    secret: tls-secret

  server:
    port: &hiPort 25553

  connection:
    endpoints:
      default:
        port: *hiPort
        path: /
        ingress: True

  credentials:
    cloud:
      accessKey: *cloudKey
      secretKey: *cloudSecret
    apiwrapper:
      username: *apiwrapperUser
      password: *apiwrapperPass
    api:
      username: *apiUser
      password: *apiPass
    rawdata:
      username: *rawdataUser
      password: *rawdataPass
    rul:
      username: *hiUser
      password: *hiPass

  configuration:
    properties: |-
      spring.application.name=rulbackendservice
      spring.jpa.open-in-view=false
      edc.apiwrapper.submodelPath=api/service
      edc.apiwrapper.submodel=submodel
      edc.apiwrapper.providerEdcUrlKey=provider-connector-url
      security.api.endpoints.ruldatareceiver.notifyresult.noauth=true
      ruldb.drivername=org.postgresql.Driver
      ruldb.show-sql=false
      ruldb.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      ruldb.hibernate.hbm2ddl.auto=update
      ruldb.url=jdbc:postgresql://ruldb:57999/rul
      rawdatadb.drivername=org.postgresql.Driver
      rawdatadb.show-sql=false
      rawdatadb.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      rawdatadb.hibernate.hbm2ddl.auto=update
      server.port=25554
      cloud.endpoint=https://dlr-minio.dev.demo.catena-x.net/
      cloud.region=eu-west-1
      cloud.bucket=test
      cloud.inputFile.bucketName=testbucket
      cloud.inputFile.key=testfile
      edc.apiwrapper.url=https://apiw-dlr.dev.demo.catena-x.net/
      requester.rulresult.endpoint=http://edc.requester.com/endpoint
      requester.bpn=BPN0000REQUESTER
      requester.rulresult.resultAssetName=urn:example:id
      supplier.rulservice.endpoint=http://edc.supplier.com/endpoint
      supplier.bpn=BPN0000SUPPLIER
      supplier.rulservice.inputAssetName=urn:example:id
      edc.bpn=BPN0000OEM
      edc.endpoint=https://dlr.dev.demo.catena-x.net
      security.api.role=USER

rawdatadb:
  fullnameOverride: "rawdatadb"
  image:
    pullPolicy: Always
  auth:
    database: &psqlDatabase "rawdata"
    username: *rawdataUser
    password: *rawdataPass

  persistence:
    enabled: false

  # initdbUsername: *psqlUsername
  # initdbPassword: *psqlPassword

ruldb:
  fullnameOverride: "ruldb"
  image:
    pullPolicy: Always
  auth:
    database: &psqlDatabase "rul"
    username: *hiUser
    password: *hiPass

  persistence:
    enabled: false

  # initdbUsername: *psqlUsername
  # initdbPassword: *psqlPassword