---
apiVersion: v2
name: all-in-one
description: Deploys postgres, hiapp, updater and provider
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.0.1"
version: 0.0.1
maintainers: []

dependencies:
  - name: postgresql
    version: "12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: rawdatadb
  - name: postgresql
    version: "12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: healthindicatordb
  - name: oem-hi-app
    version: "0.0.1"
    repository: file://../hiapp
  - name: provider
    version: "0.0.1"
    repository: file://../provider
  - name: updater
    version: "0.0.1"
    repository: file://../updater

