---
apiVersion: v2
name: all-in-one
description: Deploys postgres, hiapp, updater and provider
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.1.0"
version: 0.1.0
maintainers: []

dependencies:
  - name: postgresql
    version: "12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: rawdatadb
  - name: postgresql
    version: "12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: healthindicatordb
  - name: oem-hi-app
    version: "0.1.0"
    repository: file://../hiapp
  - name: product-hi-supplier-service
    version: "0.1.0"
    repository: file://../hisuppliermock
  - name: provider
    version: "0.1.0"
    repository: file://../provider
  - name: updater
    version: "0.1.0"
    repository: file://../updater
  - name: oem-hi-frontend
    version: "0.1.0"
    repository: file://../hifrontend
  - name: postgresql
    version: ">=12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: ruldb
  - name: oem-rul-backend
    version: "0.1.0"
    repository: file://../rulbackend
