---
apiVersion: v2
name: all-in-one-int
description: All-in-one integration chart
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.1.0"
version: 0.1.0
maintainers: []

dependencies:
#  - name: postgresql
#    version: "12.1.2"
#    repository: https://charts.bitnami.com/bitnami
#    alias: rawdatadb
#  - name: postgresql
#    version: "12.1.2"
#    repository: https://charts.bitnami.com/bitnami
#    alias: healthindicatordb
#  - name: oem-hi-app
#    version: "0.1.0"
#    repository: file://../hiapp
#  - name: hisuppliermock
#    version: "0.1.0"
#    repository: file://../hisuppliermock
#  - name: provider
#    version: "0.1.0"
#    repository: file://../provider
#  - name: updater
#    version: "0.1.0"
#    repository: file://../updater
#  - name: oem-hi-frontend
#    version: "0.1.0"
#    repository: file://../hifrontend
#  - name: postgresql
#    version: ">=12.1.2"
#    repository: https://charts.bitnami.com/bitnami
#    alias: ruldb
#  - name: oem-rul-backend
#    version: "0.1.0"
#    repository: file://../rulbackend
  - name: postgresql
    version: "12.1.2"
    repository: https://charts.bitnami.com/bitnami
    alias: peakloaddb
  - name: sedc-oem-datacollector
    version: "0.1.0"
    repository: file://../sedcdatacollector
  - name: sedc-oem-calculator
    version: "0.1.0"
    repository: file://../sedccalculator
  - name: oem-edr-proxy
    version: "0.1.0"
    repository: file://../edrproxy